export const INCREMENT_DATE = "INCREMENT_DATE";
export const DECREMENT_DATE = "DECREMENT_DATE";
export const SET_PLACES = "SET_PLACES";
export const SET_EVENTS = "SET_EVENTS";
export const FONTS_LOADED = "FONTS_LOADED";
export const FONTS_LOADING = "FONTS_LOADING";
export const COORDS_LOADED = "COORDS_LOADED";
export const COORDS_LOADING = "COORDS_LOADING";
export const SET_LATITUDE = "SET_LATITUDE";
export const SET_LONGITUDE = "SET_LONGITUDE";

export const SET_PLACES_MARKERS = "SET_PLACES_MARKERS";
export const SET_EVENTS_MARKERS = "SET_EVENTS_MARKERS";
export const SET_MAP_COORDINATES = "SET_MAP_COORDINATES";
export const SET_INITIAL_REGION = "SET_INITIAL_REGION";
export const SET_TYPE_MARKERS = "SET_TYPE_MARKERS";

export const PLACES_MARKERS_LOADED = "PLACES_MARKERS_LOADED ";
export const EVENTS_MARKERS_LOADED = "EVENTS_MARKERS_LOADED";

export const SET_SEARCH_PHRASE = "SET_SEARCH_PHRASE";
export const SET_SEARCH_TYPE = "SET_SEARCH_TYPE";
export const SET_SEARCH_CATEGORIES = "SET_SEARCH_CATEGORIES";
export const SET_SEARCH_DATE_FROM = "SET_SEARCH_DATE_FROM";
export const SET_SEARCH_DATE_TO = "SET_SEARCH_DATE_TO";

export const SET_PLACES_CATEGORIES = "SET_PLACES_CATEGORIES";
export const SET_EVENTS_CATEGORIES = "SET_EVENTS_CATEGORIES";

export const SET_STEP = "SET_STEP";
export const SET_RESULTS = "SET_RESULTS";

export const SET_EVENT = "SET_EVENT";

export const SET_USER_PASSWORD = "SET_USER_PASSWORD";
export const SET_USER_MAIL = "SET_USER_MAIL";
export const SET_USER_LOGIN = "SET_USER_LOGIN";
export const SET_USER_LOGOUT = "SET_USER_LOGOUT";
export const SET_USER_ID = "SET_USER_ID";

export const SET_FAVORITES_PLACES = "SET_FAVORITES_PLACES";
export const SET_FAVORITES_EVENTS = "SET_FAVORITES_EVENTS";
export const SET_PLAN_EVENTS = "SET_PLAN_EVENTS";
