//MAP ACTIONS
export const SET_COORDS = "SET_MAP_COORDINATES";
export const COORDS_LOADED = "COORDS_LOADED";
//MARKERS ACTIONS
export const EVENTS_MARKERS_LOADED = "EVENTS_MARKERS_LOADED";
export const PLACES_MARKERS_LOADED = "PLACES_MARKERS_LOADED ";
export const SET_PLACES_MARKERS = "SET_PLACES_MARKERS";
export const SET_EVENTS_MARKERS = "SET_EVENTS_MARKERS";
export const SET_TYPE_MARKERS = "SET_TYPE_MARKERS";
//SEARCH ACTIONS
export const SET_SEARCH_PHRASE = "SET_SEARCH_PHRASE";
export const SET_SEARCH_TYPE = "SET_SEARCH_TYPE";
export const SET_SEARCH_CATEGORIES = "SET_SEARCH_CATEGORIES";
export const SET_SEARCH_DATE_FROM = "SET_SEARCH_DATE_FROM";
export const SET_SEARCH_DATE_TO = "SET_SEARCH_DATE_TO";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
//USER ACTIONS
export const SET_USER_PASSWORD = "SET_USER_PASSWORD";
export const SET_USER_MAIL = "SET_USER_MAIL";
export const SET_USER_ID = "SET_USER_ID";
export const SET_USER_LOGGED = "SET_USER_LOGGED";
//CATEGORIES ACTIONS
export const SET_PLACES_CATEGORIES = "SET_PLACES_CATEGORIES";
export const SET_EVENTS_CATEGORIES = "SET_EVENTS_CATEGORIES";
//FAVORITES ACTIONS
export const SET_FAVORITES_PLACES = "SET_FAVORITES_PLACES";
export const SET_FAVORITES_EVENTS = "SET_FAVORITES_EVENTS";
//FONTS ACTIONS
export const FONTS_LOADED = "FONTS_LOADED";
//PLAN ACTIONS
export const SET_PLAN_EVENTS = "SET_PLAN_EVENTS";
//EVENT ACTIONS
export const SET_EVENT = "SET_EVENT";
